---
title: Speed to send first candidate
authors:
- Kael Huerta
tags:
- knowledge
- jobs
- matching
- first-candidate
- glm
- splines
created_at: 2016-10-26
updated_at: 2016-10-26
tldr: We compare the cancellation probability of a job in terms of the time it took our team to send the first candidate from the time the job was posted and the time it was claimed. We assess if it is worth speeding up the matching process.
---

**Contents**

[TOC]

### Main Result

This research suggests that within the first week after the job was claimed,
there is no gain in hurrying the first candidate sent. After a week we can see
how the probability of cancellation starts increasing.

<!-- Loading libraries  -->

```{r libraries, echo = F, message = F}
## Required libraries
library(arm)
library(stringr)
library(plyr)
library(dplyr)
library(dtplyr)
library(data.table)
library(lubridate)
library(ggplot2)
library(tidyr)
library(bigrquery)
library(gridExtra)
library(splines)
library(forcats)
library(knitr)

## Changing the ggplot default theme
theme_set(theme_bw())

## Colorblind-friendly palette
pal <- c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442",
  "#0072B2", "#D55E00", "#CC79A7", "#000000")

## For BQ not complaining about the interactive environment
options('httr_oob_default' = T)
```

```{r}
getwd()
```


```{r data, echo = F}
# project <- 'toptal.com:api-project-726361118046'
# pd <- src_bigquery(project, 'analytics_warehouse_prototype')
# 
# jobs <- tbl(pd, 'jobs_csv') %>%
#   as.data.table
# 
# statuses <- tbl(pd, 'statuses') %>%
#   filter(statusable_type == 'Job') %>%
#   as.data.table
# 
# funnel <- tbl(pd, 'job_matching_funnel_dataset') %>%
#   select(job_id, job_posted_at, job_claimed_at, first_candidate_sent_at) %>%
#   as.data.table
# 
# actions <- tbl(pd, 'performed_actions') %>%
#   filter(subject_type == 'Job') %>%
#   as.data.table
load('models.RData')
```

```{r models, echo = F, message = F}
## Change this to update the report
# end.date <- as.POSIXct('2016-10-24') - days(14)
# 
# ## Let's get jobs posted from new clients (never had posted a job before)
# first.job <- jobs %>%
#   ## Filtering long shots
#   filter(!long_shot,
#     job_status %in% c('active', 'closed', 'removed')) %>%
#   select(company_id, job_created_at, job_id, job_status, engagement_id,
#     job_type) %>%
#   tbl_df() %>% ## top_n only works on tbls, no data.tables =(
#   group_by(company_id) %>%
#   arrange(company_id, job_created_at) %>%
#   top_n(n = 1, wt = job_created_at) %>%
#   data.table
# 
# ## Let's get the cancellation timestamp
# cancelled <- statuses %>%
#   filter(status == 'removed', is.na(ended_at)) %>%
#   select(statusable_id, created_at) %>%
#   unique %>%
#   setnames(c('job_id', 'cancelled_at'))
# 
# ## Jobs that got sent away or postponed AND resumed
# resumed <- actions %>%
#   filter(str_detect(action, 'resume')) %>%
#   tbl_df() %>%
#   group_by(subject_id) %>%
#   arrange(subject_id, created_at) %>%
#   top_n(n = -1, wt = created_at) %>%
#   select(subject_id, created_at) %>%
#   as.data.table %>%
#   setnames(c('job_id', 'resumed_at'))
# 
# ## Removed due to sent away. This must be filtered
# sent.away <- actions %>%
#   arrange(subject_id, created_at) %>%
#   group_by(subject_id) %>%
#   mutate(from = c(NA, action[-length(action)]),
#     step = paste(from, action, sep = ' -> ')) %>%
#   filter(step == 'sent_away -> removed') %>%
#   select(subject_id, created_at, step)
# 
# dataset <- first.job %>%
#   join(funnel) %>%
#   join(cancelled) %>%
#   join(resumed) %>%
#   filter(!job_id %in% sent.away$subject_id, ## Filter out the sent away
#     job_posted_at < end.date, ## Filter out the recent ones
#     job_type == 'developer', ## Only developers for now
#     is.na(first_candidate_sent_at) == !is.na(cancelled_at)) %>% ## Only
#   ## the ones cancelled in this particular step of the funnel are relevant
#   mutate(cancelled = as.factor(is.na(first_candidate_sent_at)),
#     first_candidate_sent_at = as.POSIXct(ifelse(is.na(first_candidate_sent_at),
#       cancelled_at, first_candidate_sent_at), origin = origin),
#     posted = job_posted_at,
#     claimed = as.POSIXct(ifelse(!is.na(resumed_at) &
#       resumed_at < first_candidate_sent_at,
#       resumed_at, job_claimed_at), origin = lubridate::origin),
#     claim.to.first = as.numeric(difftime(first_candidate_sent_at, claimed,
#       units = 'days')),
#     post.to.first = as.numeric(difftime(first_candidate_sent_at, job_posted_at,
#       units = 'days')),
#     daily.delay = cut(claim.to.first, right = F,
#       breaks = c(0, 1, 2, 3, 4, 5, 6, 7, 14, 31)),
#     delay = cut(claim.to.first, right = F,
#       breaks = c(0, 1, 3, 5, 7, 14, 31))) %>% 
#   mutate(cv.sample = 1:nrow(.) %% 5)

## Posted to First Sent Model
set.seed(3003)
post.mod <- dataset %>%
  filter(post.to.first < 31,
    is.na(resumed_at) | resumed_at > first_candidate_sent_at) %>%
  bayesglm(formula = cancelled ~
      bs(post.to.first, df = 10, Boundary.knots = c(0, 31))
    ,
    prior.df = 1,
    prior.scale = rep(.01, 10),
    family = binomial(link = 'logit'))

## Claimed to First Sent Model
set.seed(3003)
claim.mod <- dataset %>%
  filter(claim.to.first < 31) %>%
  bayesglm(formula = cancelled ~
      bs(claim.to.first, df = 10, Boundary.knots = c(0, 31))
    ,
    prior.df = 1,
    prior.scale = rep(.03, 10),
    family = binomial(link = 'logit'))

```

```{r, echo = F}
display(post.mod, 3)
```

```{r, echo = F}
display(claim.mod, 3)
```
